# Generated by Django 3.2.5 on 2021-08-04 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20210720_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='exchange',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exchange.exchange', verbose_name='related exchange'),
        ),
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='exchange user'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='exchange',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_exchange', to='exchange.exchange', verbose_name='related exchange'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_user', to=settings.AUTH_USER_MODEL, verbose_name='exchange user'),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'CREATED'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='IN_PROGRESS', max_length=50, verbose_name='payment status'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'CREATED'), ('FAILED', 'FAILED'), ('SUCCESS', 'SUCCESS')], default='IN_PROGRESS', max_length=50, verbose_name='payment status'),
        ),
    ]
