# Generated by Django 3.2.5 on 2021-08-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210804_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
