# Generated by Django 3.2.5 on 2022-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210808_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymenttransaction',
            name='transaction_request',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='transaction request log'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_request',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='transaction request log'),
        ),
        migrations.AlterField(
            model_name='historicalpaymenttransaction',
            name='transaction_response',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='transaction response log'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_response',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='transaction response log'),
        ),
    ]
