"""
Django settings for submetering project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import ugettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_TEMPLATE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-eq*^5sz77feu=#v^bn8m6wyt4sz-dey-ujzl_$epe4qi_q5^im"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

DOMAIN = "127.0.0.1:8000"

ALLOWED_HOSTS = ["*"]

AUTH_USER_MODEL = "authentication.User"

# Application definition

INSTALLED_APPS = [
    "payment",
    "simple_history",
    "order",
    "authentication",
    "django.contrib.admin",
    "oauth2_provider",
    "rest_framework",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'panel',
    'exchange',
    'cacheops'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    'django.middleware.locale.LocaleMiddleware'
]

ROOT_URLCONF = "vaccine.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vaccine.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGE_CHOICES = (
    ('en', 'English'),
    ('tr', 'Turkish'),
    ('es', 'Spanish'),
    ('fa', 'Farsi'),
)

LANGUAGES = (
    ('en', _('English')),
    ('tr', _('Turkish')),
    ('es', _('Spanish')),
    ('fa', _('Farsi')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/backend/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static_files")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ),
}

DOMAIN = "http://127.0.0.1:8000"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"
PORTAL_API_KEY = "c8c43f68-1e7e-4b5f-b633-7ef3dadfa8d6"

LOGIN_URL = "/panel/login"

MAX_WRONG_PIN_NUMBER = 5

API_KEYS = {
    "143314ed-8f31-4312-b394-019e536be65e": "AsanPardakht",
    "ba7e3f3c-5361-42c9-aeb1-b084be104c6f": "Mashverap"
}

SUPER_PAY_URL = "https://thirdparty.superpay.com.tr"

EXTERNAL_API_KEY = "51534166-2c9b-4acb-b8db-5421b54d4bd7"
