# Generated by Django 3.2.5 on 2021-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20210808_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalexchange',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='historicalexchange',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
