# Generated by Django 3.2.5 on 2021-07-11 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='user country'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('gender', models.CharField(max_length=50, verbose_name='gender')),
                ('nationality', models.CharField(max_length=50, verbose_name='nationality')),
                ('passport_number', models.CharField(max_length=50, verbose_name='passport number')),
                ('passport_exp_date', models.DateField(verbose_name='passport expiration date')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('birth_country', models.CharField(max_length=50, verbose_name='birth country')),
                ('national_id', models.CharField(max_length=50, verbose_name='national id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
    ]
