# Generated by Django 3.2.5 on 2021-07-11 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210711_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid'),
        ),
    ]
