# Generated by Django 3.2.5 on 2021-07-13 08:55

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210711_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=authentication.models.otp_gen, verbose_name='otp code')),
                ('is_used', models.BooleanField(default=False, verbose_name='has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
            options={
                'verbose_name': 'otp',
                'verbose_name_plural': 'otps',
            },
        ),
    ]
