# Generated by Django 3.2.5 on 2021-07-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='passport_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='passport image'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passports/% Y/% m/% d/', verbose_name='passport image'),
        ),
    ]
