# Generated by Django 3.2.5 on 2022-01-17 12:01

from django.db import migrations, models
import utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.functions.get_file_path, verbose_name='passport image'),
        ),
    ]
