# Generated by Django 3.2.5 on 2021-07-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='transport_company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport_company_name',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose1_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose 1 arrival date'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose1_transport_company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 transportation company name'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose 1 arrival date'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 flight number'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_transport_company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 transportation company name'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose1_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose 1 arrival date'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose1_transport_company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 transportation company name'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose 1 arrival date'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 flight number'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_transport_company_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 transportation company name'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='dose1_flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 flight number'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WAITING_FOR_DATA_SUBMISSION', 'waiting for data submisson'), ('PAID', 'Paid'), ('WAITING_FOR_SETTING_FIRST_DOSE', 'Waiting for setting first dose'), ('WAITING_FOR_RECEIVING_FIRST_DOSE', 'Waiting for receiving first dose'), ('WAITING_FOR_SETTING_SECOND_DOSE', 'Waiting for setting second dose'), ('WAITING_FOR_RECEIVING_SECOND_DOSE', 'Waiting for receiving second dose'), ('DONE', 'Done')], default='OPEN', max_length=50, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dose1_flight_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose 1 flight number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WAITING_FOR_DATA_SUBMISSION', 'waiting for data submisson'), ('PAID', 'Paid'), ('WAITING_FOR_SETTING_FIRST_DOSE', 'Waiting for setting first dose'), ('WAITING_FOR_RECEIVING_FIRST_DOSE', 'Waiting for receiving first dose'), ('WAITING_FOR_SETTING_SECOND_DOSE', 'Waiting for setting second dose'), ('WAITING_FOR_RECEIVING_SECOND_DOSE', 'Waiting for receiving second dose'), ('DONE', 'Done')], default='OPEN', max_length=50, verbose_name='order status'),
        ),
    ]
