# Generated by Django 3.2.5 on 2021-07-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210719_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='order amount in lira'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='order amount in lira'),
        ),
    ]
