# Generated by Django 3.2.5 on 2021-07-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210719_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='amount',
            field=models.FloatField(default=0, verbose_name='order amount in lira'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0, verbose_name='order amount in lira'),
        ),
    ]
