# Generated by Django 3.2.5 on 2021-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210720_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL')], max_length=50, null=True, verbose_name='payment type'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL')], max_length=50, null=True, verbose_name='payment type'),
        ),
    ]
