# Generated by Django 3.2.5 on 2021-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210730_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='order paid amount in lira'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='payment date'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='order paid amount in lira'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='payment date'),
        ),
    ]
