# Generated by Django 3.2.5 on 2021-08-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210802_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='dose1_next_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose1 next vaccination date'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose1_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose1 vaccination date'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose1_vaccine_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.vaccinecenter', verbose_name='dose1 vaccine center'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose1_vaccine_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose1 vaccine type'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_next_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose2 next vaccination date'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose2 vaccination date'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_vaccine_center',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.vaccinecenter', verbose_name='dose2 vaccine center'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='dose2_vaccine_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose2 vaccine type'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose1_next_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose1 next vaccination date'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose1_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose1 vaccination date'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose1_vaccine_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose1_orders', to='order.vaccinecenter', verbose_name='dose1 vaccine center'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose1_vaccine_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose1 vaccine type'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_next_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose2 next vaccination date'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='dose2 vaccination date'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_vaccine_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose2_orders', to='order.vaccinecenter', verbose_name='dose2 vaccine center'),
        ),
        migrations.AddField(
            model_name='order',
            name='dose2_vaccine_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dose2 vaccine type'),
        ),
    ]
