# Generated by Django 3.2.5 on 2021-08-04 10:36

from django.db import migrations, models
import utils.functions


def generate_last_codes(app, schema_editor):
    Order = app.get_model('order', 'Order')
    for row in Order.objects.all():
        row.code = utils.functions.code_generator()
        row.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210802_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='code',
            field=models.CharField(blank=True, default=utils.functions.code_generator, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default=utils.functions.code_generator, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('EXCHANGE', 'EXCHANGE')], max_length=50, null=True, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('EXCHANGE', 'EXCHANGE')], max_length=50, null=True, verbose_name='payment type'),
        ),
        migrations.RunPython(generate_last_codes, reverse_code=migrations.RunPython.noop),
    ]
