# Generated by Django 3.2.5 on 2021-10-03 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_auto_20210808_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('vaccine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='vaccine type')),
                ('is_available', models.BooleanField(default=True, verbose_name='is vaccine type available?')),
            ],
            options={
                'verbose_name': 'vaccine type',
                'verbose_name_plural': 'vaccine types',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVaccineType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('vaccine_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='vaccine type')),
                ('is_available', models.BooleanField(default=True, verbose_name='is vaccine type available?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vaccine type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='dose1_vaccine_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.vaccinetype', verbose_name='vaccine type'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='dose2_vaccine_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.vaccinetype', verbose_name='vaccine type'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.vaccinetype', verbose_name='vaccine type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dose1_vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose1_orders', to='order.vaccinetype', verbose_name='vaccine type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dose2_vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose2_orders', to='order.vaccinetype', verbose_name='vaccine type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_orders', to='order.vaccinetype', verbose_name='vaccine type'),
        ),
    ]
