# Generated by Django 3.2.5 on 2022-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220106_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='wrong_coupon_count',
            field=models.IntegerField(default=0, verbose_name='wrong coupons counter'),
        ),
        migrations.AddField(
            model_name='order',
            name='wrong_coupon_count',
            field=models.IntegerField(default=0, verbose_name='wrong coupons counter'),
        ),
    ]
