# Generated by Django 3.2.5 on 2022-01-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220106_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='off_percent',
            field=models.FloatField(default=15, verbose_name='coupon off percent'),
        ),
        migrations.AddField(
            model_name='historicalcoupon',
            name='off_percent',
            field=models.FloatField(default=15, verbose_name='coupon off percent'),
        ),
    ]
