# Generated by Django 3.2.5 on 2022-01-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_historicalhotelpackage_hotelpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhotelpackage',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='english address'),
        ),
        migrations.AlterField(
            model_name='historicalhotelpackage',
            name='address_fa',
            field=models.TextField(blank=True, null=True, verbose_name='farsi address'),
        ),
        migrations.AlterField(
            model_name='historicalhotelpackage',
            name='address_tr',
            field=models.TextField(blank=True, null=True, verbose_name='turkish address'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='english address'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='address_fa',
            field=models.TextField(blank=True, null=True, verbose_name='farsi address'),
        ),
        migrations.AlterField(
            model_name='hotelpackage',
            name='address_tr',
            field=models.TextField(blank=True, null=True, verbose_name='turkish address'),
        ),
    ]
