# Generated by Django 3.2.5 on 2022-01-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20220108_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='hotel_package',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.hotelpackage', verbose_name='hotel package'),
        ),
        migrations.AddField(
            model_name='order',
            name='hotel_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_package_orders', to='order.hotelpackage', verbose_name='hotel package'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='amount',
            field=models.FloatField(default=0, verbose_name='order amount in euro'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='order paid amount in euro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0, verbose_name='order amount in euro'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.FloatField(default=0, verbose_name='order paid amount in euro'),
        ),
    ]
