# Generated by Django 3.2.5 on 2022-01-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20220108_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhotelpackage',
            name='room_type_en',
            field=models.TextField(blank=True, null=True, verbose_name='room type in english'),
        ),
        migrations.AddField(
            model_name='historicalhotelpackage',
            name='room_type_fa',
            field=models.TextField(blank=True, null=True, verbose_name='room type in farsi'),
        ),
        migrations.AddField(
            model_name='historicalhotelpackage',
            name='room_type_tr',
            field=models.TextField(blank=True, null=True, verbose_name='room type in turkish'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='room_type_en',
            field=models.TextField(blank=True, null=True, verbose_name='room type in english'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='room_type_fa',
            field=models.TextField(blank=True, null=True, verbose_name='room type in farsi'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='room_type_tr',
            field=models.TextField(blank=True, null=True, verbose_name='room type in turkish'),
        ),
    ]
