# Generated by Django 3.2.5 on 2022-01-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_currencyexchangerate_historicalcurrencyexchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='usdt_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='usdt token'),
        ),
        migrations.AddField(
            model_name='order',
            name='usdt_token',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='usdt token'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('EXCHANGE', 'EXCHANGE'), ('USDT', 'USDT')], max_length=50, null=True, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIAL', 'PARTIAL'), ('EXCHANGE', 'EXCHANGE'), ('USDT', 'USDT')], max_length=50, null=True, verbose_name='payment type'),
        ),
    ]
