# Generated by Django 3.2.5 on 2022-01-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20220122_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency_name',
            field=models.CharField(blank=True, choices=[('IRR', 'Iranian rial'), ('USDT', 'usdt')], max_length=5, null=True, verbose_name='currency ISO code'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencyexchangerate',
            name='currency_name',
            field=models.CharField(blank=True, choices=[('IRR', 'Iranian rial'), ('USDT', 'usdt')], max_length=5, null=True, verbose_name='currency ISO code'),
        ),
    ]
