# Generated by Django 3.2.5 on 2022-01-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20220123_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='usdt_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='usdt payment ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='usdt_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='usdt payment ID'),
        ),
    ]
