# Generated by Django 3.2.5 on 2022-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20220124_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhotelpackage',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='hotel image'),
        ),
        migrations.AddField(
            model_name='historicalhotelpackage',
            name='rank',
            field=models.FloatField(default=0, verbose_name='hotel star number'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels', verbose_name='hotel image'),
        ),
        migrations.AddField(
            model_name='hotelpackage',
            name='rank',
            field=models.FloatField(default=0, verbose_name='hotel star number'),
        ),
    ]
